### ISSUE TITLE
curl client: http methods beyond GET and POST don't work

### ISSUE THREAD

**Issue by atufkas** [sonrisa/restclient-component#9]
Hi Nil,

your loyal lib user and contributor again found some major bug...: The curl implementation doesn't correctly set the curl options for methods other than GET and POST. It simply doesn't work since either the method is not set (for PUT) or the url is left blank (for every other method).

I'm going to submit a patch and open a pull request soon.

Cheers,
Matthias

**Comment by nilopc** [comment]
This sounds critical. Indeed it should be fixed. We should rewrite the test to be more strict too.

**Comment by atufkas** [comment]
Yeah, I already did that to a certain extent (see my comment with pull request). Great you're currently online - would you mind tagging again as soon as you integrated that patch (and probably some additions or other stuff)?

Thanks!
